### ISSUE TITLE
Картинки указанные в .md как относительные в .html должны быть по тому же URL

### ISSUE THREAD

**Issue by vithar** [vithar/bem.info#20]
У меня был реализован механизм указания картинок по относительному пути рядом с .md (см. https://github.com/bem/bem-method/tree/bem-info-data/method/key-concepts)

В новой версии этот механизм утерян, надо вернуть как было: при обработке .md файла копировать все картинки рядом с ним в его результирующую папку и ссылаться на картинки относительно, без указания хоста:

```
<img src='key-concepts__head_marked.png' alt=''>
```

**Comment by tormozz48** [comment]
Ну, это не баг а фича. 
Так предусмотрено в логике горшочка.

Можно подумать про отдельный шаг в сборке в котором происходит загрузка изображений

@tadatuta ?

**Comment by vithar** [comment]
Это регрессия по отношению к тому, как было реализовано до этого.

**Comment by tadatuta** [comment]
я за то, чтобы сделать отдельные таски про каждый этап и чтобы финальная версия собирала картинки из произвольных сорцов и складывала в единую папку `static`

**Comment by tormozz48** [comment]
@tadatuta +1

**Comment by tormozz48** [comment]
> я за то, чтобы сделать отдельные таски про каждый этап и чтобы финальная версия собирала картинки из произвольных сорцов и складывала в единую папку

Мне нужно будет: 
1. находить ссылки на картинки
2. резолвить их абсолютные пути на удаленный ресурс или локальную файловую систему
3. загружать файлы изображений
4. складывать их в папку static
5. менять ссылки и уводить их на папку static

**Comment by tormozz48** [comment]
при этом картинки должны сохраняться с уникальными именами чтобы избежать конфликтов

**Comment by tadatuta** [comment]
> менять ссылки и уводить их на папку static

думаю, что это должна быть таска, которая по умолчанию делает как ты написал, но может принимать кастомную функцию-резолвер, которая на вход получит исходный путь и вернет тот, который подставится в финальный HTML

> при этом картинки должны сохраняться с уникальными именами чтобы избежать конфликтов

в идеале картинки должны хешироваться по контенту

**Comment by tormozz48** [comment]
> в идеале картинки должны хешироваться по контенту

я это и подразумевал

**Comment by vithar** [comment]
Ок, давайте хешировать по контенту функцией из борщика. Только складывать в /, а не в /static в финальном output.

**Comment by tormozz48** [comment]
А может вообще инлайнить картинки в html ?

**Comment by vithar** [comment]
Не надо.

**Comment by tadatuta** [comment]
`/` должен быть частным случаем произвольного пути
