### ISSUE TITLE
При отсутствии интернета сборка даёт страницы без контента

### ISSUE THREAD

**Issue by vithar** [vithar/bem.info#26]
1. Запустить `gulp`, дождаться окончания сборки
2. Убедиться, что страницы из `.md` показываются нормально
3. Убить `gulp`
4. Выключить wi-fi
5. Запустить `gulp` ещё раз
6. Cтраницы из `.md` показываются без контента

Было обещано, что если интернета нет, используется последняя актуальная версия кеша, чего сейчас не происходит.

Надо сделать так, чтобы можно было разрабатываться в самолёте.

**Comment by tormozz48** [comment]
Про это есть задача https://github.com/bem-site/gorshochek/issues/27
