### ISSUE TITLE
Поддержать относительный путь до index.min.*

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#27]
Нужно для нормальной работы сайта на `gh-pages` и для возможности поднимать отдельные версии в подпапках.

**Comment by vithar** [comment]
Не вижу необходимости ни в первом, ни во втором. Зачем на это тратить время?

**Comment by tadatuta** [comment]
Например, чтобы выкатываться не прямо в продакшен, а сначала на дев или чтобы мочь использовать сайт локально без поднятия сервера.

Это не срочно, конечно, но не кажется чем-то требующим много времени, удобнее станет.

**Comment by vithar** [comment]
Одновременно с этим вы отказались от локальной загрузки картинок по месту и хотите складывать их в /static.

Противоречие я вижу тут.

**Comment by tadatuta** [comment]
Наоборот же. Были ссылки относительно произвольного источника, а станут — относительно локальной папки со статикой.

**Comment by vithar** [comment]
Будет /static/index.min.css (или просто /index.min.css), потому что высчитывать для каждой страницы путь ../../../ как-то не очень.

**Comment by tadatuta** [comment]
Вижу в этом я большой проблемы не: https://github.com/tadatuta-studio/greenzbi/blob/master/common.blocks/root/root.bemtree.js#L27

**Comment by vithar** [comment]
Сделал возможность указывать `root` в `data.root` и добавил его использование везде.

Теперь можно выкладывать на gh-pages (`./deploy.sh git@github.com:vithar/bem.info.git`)
http://vithar.github.io/bem.info/ru/
http://vithar.github.io/bem.info/ru/methodology/

Локально стало так:
http://localhost:8008/bem.info/ru/
http://localhost:8008/bem.info/ru/methodology/
