### ISSUE TITLE
Добавить слак Веб-стандартов

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#31]

**Comment by vithar** [comment]
Добавил в подвал
http://vithar.github.io/bem.info/ru/
http://vithar.github.io/bem.info/ru/methodology/

**Comment by tadatuta** [comment]
я уже после того, как ты написал, что оно в подвале, секунд 20 пытался найти, где именно.
у меня слепота на такие ссылки в подвале. они всем своим видом говорят, что там какая-то ненужная ерунда. но, наверное, нам и не очень важно, чтобы они были на виду.
