### ISSUE TITLE
Социальщина

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#32]
Лайки, шары, вот это все

**Comment by vithar** [comment]
Не хочу лайки/шары вот это всё. Оно выглядит ужасно.

**Comment by tadatuta** [comment]
Так оно может выглядеть совершенно произвольным образом.
А польза все-таки есть.

**Comment by vithar** [comment]
Тогда нужен дизайн, давай в среду про это поговорим с Димой.

**Comment by tadatuta** [comment]
http://sapegin.github.io/social-likes/

**Comment by vithar** [comment]
@tadatuta, а почему не https://github.com/bem-contrib/bem-social ?

**Comment by tadatuta** [comment]
@vithar не знаю, давай отревьюируем и, если все ок, заиспользуем.
мне вообще подошла бы стандарная яндексовая Поделиська, я привел первую попавшуюся ссылку, которая бы отвечала на твою претензию, что соцкнопки выглядят как говно )

**Comment by vithar** [comment]
https://github.com/vithar/bem.info/pull/68
