### ISSUE TITLE
Ссылка на источник статьи на gh для отправки правок

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#33]

**Comment by tormozz48** [comment]
Горшочек может предоставить данные для построения такой ссылки в шаблонах. Нужно лишь включить некоторые опции

**Comment by AnyaTyu** [comment]
@tormozz48 какие опции надо включить?

Надо сконструировать ссылку вида

```
http://prose.io/#bem/bem-method/blob/bem-info-data/method/key-concepts/key-concepts.ru.md
```
