### ISSUE TITLE
Поддержать теги

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#34]

**Comment by tormozz48** [comment]
Горшочек это умеет.

**Comment by vithar** [comment]
Горшочек-то умеет, но мне нужно их к заголовку страницы прилепить по дизайну и я пока не придумал как.

**Comment by vithar** [comment]
Реализовал (https://github.com/vithar/bem.info/commit/fb39c84d07002e1d0038dad5084c31bebf9d661e). Нужен будет рефакторинг по лайауту после перехода md2bemjson (выводить сначала заголовок страницы, а потом уже `article-tags`).
