### ISSUE TITLE
Держать в исходниках несжатые svg, сжимать на этапе деплоя

### ISSUE THREAD

**Issue by tadatuta** [vithar/bem.info#36]

**Comment by vithar** [comment]
Я сжимаю через zopfli с многими проходами, получается меньше, но сильно-сильно дольше.

И не вижу смысла оптимизировать при деплое, рассматривай их как png, которые один раз после редактирования прогоняются через ImageOptim.

**Comment by vithar** [comment]
Если svg лежит как svgz, значит я над ним уже поработал и прогнал его через все возможные оптимизации, лучше уже не будет.

**Comment by tadatuta** [comment]
png после imageOptim мой редактор показывает, ну да ладно :)

**Comment by vithar** [comment]
Ну так это надо писать feature request редактору на поддержку.svgz ;)

Гитхабу, например, я написал. Тест-кейс https://github.com/vithar/svg-test/
