### ISSUE TITLE
Ссылка на форум в футере ИМХО неудачная идея

### ISSUE THREAD

**Issue by tormozz48** [vithar/bem.info#39]
Как по мне наш форум - чуть ли не главный раздел на сайте и на него люди постоянно заходят.

А если ссылка на него будет в футере, то люди будут долго и нудно искать как на него попасть.
Нужно или продублировать или перенести ссылку на форум в шапку.

@vithar @tadatuta

**Comment by vithar** [comment]
Переместили ссылку в шапку:

http://vithar.github.io/bem.info/ru/
http://vithar.github.io/bem.info/ru/methodology/
