### ISSUE TITLE
Опции кастомного md-рендерера ломают мой ссылочный переопределятор

### ISSUE THREAD

**Issue by tormozz48** [vithar/bem.info#40]
Долго не мог понять причину, почему сломался мой ссылочный переопределятор.

Нашел проблему вот в этом коде: https://github.com/vithar/bem.info/blob/master/lib/marked-opts.js#L10-L13
```
renderer._link = renderer.link;
renderer.link = function(href, title, text) {
    return this._link(href.replace(/(.*\/)([^\/#]*)(.*)/, '$1$3'), title, text);
};
```

Здесь происходит замена ссылок, которая нарушает логику переопределятора.

@vithar @tadatuta

**Comment by vithar** [comment]
Кажется это можно просто выкосить.

**Comment by tormozz48** [comment]
> Кажется это можно просто выкосить.

Ок, принял
